server.port=8081
spring.application.name=user-service


# Eureka

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


# JPA & Database 

spring.datasource.url=jdbc:postgresql://localhost:5432/ziaant_db
spring.datasource.username=ziaant
spring.datasource.password=ziaant123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Scan des packages (très important)
spring.jpa.packages-to-scan=com.ziaant.user_service


# Logging

logging.level.com.ziaant=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG