CREATE DATABASE auth_db;
CREATE DATABASE restaurant_db;
CREATE DATABASE reservation_db;
CREATE DATABASE user_db;
CREATE DATABASE notification_db;
CREATE DATABASE payment_db;

GRANT ALL PRIVILEGES ON DATABASE auth_db TO ziaant;
GRANT ALL PRIVILEGES ON DATABASE restaurant_db TO ziaant;
GRANT ALL PRIVILEGES ON DATABASE reservation_db TO ziaant;
GRANT ALL PRIVILEGES ON DATABASE user_db TO ziaant;
GRANT ALL PRIVILEGES ON DATABASE notification_db TO ziaant;
GRANT ALL PRIVILEGES ON DATABASE payment_db TO ziaant;