CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS restaurant_db;
CREATE DATABASE IF NOT EXISTS reservation_db;
CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS notification_db;
CREATE DATABASE IF NOT EXISTS payment_db;

GRANT ALL PRIVILEGES ON DATABASE auth_db TO ziaant;
GRANT ALL PRIVILEGES ON DATABASE restaurant_db TO ziaant;
GRANT ALL PRIVILEGES ON DATABASE reservation_db TO ziaant;
GRANT ALL PRIVILEGES ON DATABASE user_db TO ziaant;
GRANT ALL PRIVILEGES ON DATABASE notification_db TO ziaant;
GRANT ALL PRIVILEGES ON DATABASE payment_db TO ziaant;
