server.port=8081
spring.application.name=auth-service

#  DATABASE 

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/auth_db}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ziaant}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ziaant123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# EUREKA 

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}

eureka.instance.prefer-ip-address=true

#  JWT 
jwt.secret=${JWT_SECRET:ZiaantReserveTableCMSuperSecretKeyForJWT2025MustBe256BitsLong!}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION:300000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
jwt.expiration=${jwt.access-expiration}
auth.session-store=${AUTH_SESSION_STORE:redis}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}

# ADMIN 
admin.secret=${ADMIN_SECRET:ZIAANT_ADMIN_SECRET_2025}

# SWAGGER 
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# RABBITMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=ziaant
spring.rabbitmq.password=ziaant123
