server.port=8081
spring.application.name=auth-service

#  DATABASE 
spring.datasource.url=jdbc:postgresql://postgresql:5432/auth_db
spring.datasource.username=ziaant
spring.datasource.password=ziaant123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# EUREKA 
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

#  JWT 
jwt.secret=ZiaantReserveTableCMSuperSecretKeyForJWT2025MustBe256BitsLong!
jwt.expiration=86400000

# ADMIN 
admin.secret=ZIAANT_ADMIN_SECRET_2025

# SWAGGER 
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs