server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: ziaant
    password: ziaant123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ZiaantReserveTableCMSuperSecretKeyForJWT2025MustBe256BitsLong!
  expiration: 86400000

admin:
  secret: ZIAANT_ADMIN_SECRET_2025

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
