fichier creer et modifier :

2.1 notification-service/pom.xml
2.2 src/main/resources/application.properties
2.3 NotificationServiceApplication.java
2.4 config/SwaggerConfig.java
2.5 dto/NotificationRequest.java
2.6 dto/NotificationResponse.java
2.7 service/NotificationService.java
2.8 controller/NotificationController.java
2.9 config/RabbitMQConfig.java
2.10 listener/NotificationEventListener.java
2.11 Dockerfile (à la racine de notification-service)
2.12 Mise à jour de docker-compose.yml (à la racine du projet)
