server.port=8761

spring.application.name=eureka-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# Désactivé pour le développement académique
eureka.server.enable-self-preservation=false

# Pour éviter les problèmes de health check
management.endpoints.web.exposure.include=health,info


eureka.server.wait-time-in-ms-when-sync-empty=0


