spring.application.name=notification-service
server.port=8084

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:ziaant}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:ziaant123}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/notification_db}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=programmation235@gmail.com
spring.mail.password=urthijivxdudkbtk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

security.internal-token=${INTERNAL_SERVICE_TOKEN:change-me-in-production}
