# Application
spring.application.name=restaurant-service

server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ziaant_db
spring.datasource.username=ziaant
spring.datasource.password=ziaant123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT (meme secret que auth-service pour valider les tokens)
jwt.secret=ZiaantReserveTableCMSuperSecretKeyForJWT2025MustBe256BitsLong!



# Swagger 
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs          # ← Changer api-docs → v3/api-docs

# Désactiver Spring Security sur les endpoints Swagger
spring.security.oauth2.resourceserver.jwt.issuer-uri=

# CORS
cors.allowed-origins=http://localhost:3000

# Actuator
management.endpoints.web.exposure.include=health,info

